### ISSUE TITLE
Access thumbnail image from API

### ISSUE THREAD

**Issue by egrace479** [MorphoSource/morphosource-api#1]
Is it possible to get the thumbnail image that appears in searches as a return from the API? This is helpful for sorting out CT scans from the pictures that sometimes get uploaded along with the scans.

![Screenshot 2023-10-25 at 1 37 11 PM](https://github.com/MorphoSource/morphosource-api/assets/38985481/61753a23-838d-4ef3-be3a-30bbfa1c9507)

**Comment by JulieWinchester** [comment]
Hi! Thanks for this. I'm currently working on adding this functionality.

**Comment by JulieWinchester** [comment]
This has been implemented in API 0.6.0, as a new field on the get individual media record metadata endpoint (https://morphosource.stoplight.io/docs/morphosource-api/b474e3d7c2ccc-get-individual-media-record). 0.6.0 will go live later this evening.
