### ISSUE TITLE
Access File Object Details

### ISSUE THREAD

**Issue by egrace479** [MorphoSource/morphosource-api#2]
Is it possible to return the "File Object Details" with the API? In particular, file size is very important prior to download.

**Comment by JulieWinchester** [comment]
Hi! Yep, we should be able to do this. I'm working on it now.

**Comment by JulieWinchester** [comment]
This has been implemented in API 0.6.0, which will go live later this evening. See https://morphosource.stoplight.io/docs/morphosource-api/c7dcuud1iq44q-get-individual-media-file-metadata. Let me know if you have any questions or further requests for this endpoint!
